[package]
name = "leadr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.37", features = ["derive"] }
confy = "0.6.1"
crossterm = "0.29.0"
serde = {version = "1.0.219", features = ["derive"]}
