[package]
name = "leadr"
version = "0.3.2"
authors = ["ll-nick <github@le-large.com>"]
edition = "2024"
description = "Shell aliases on steroids"
license = "MIT"
repository = "https://github.com/ll-nick/leadr"
keywords = ["cli", "shortcuts", "terminal", "aliases", "shell"]
categories = ["cli"]

[dependencies]
clap = {version = "4.5.37", features = ["derive"] }
confy = "0.6.1"
crossterm = "0.29.0"
serde = {version = "1.0.219", features = ["derive"]}
thiserror = "2.0.12"
