[d1]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh welcome"
description = "Demo: Welcome!"
execute = true

[d2]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh insert"
description = "Demo: Insert"
execute = true

[d3]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh dynamic_content"
description = "Demo: Dynamic Content"
execute = true

[d4]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh advanced_example"
description = "Demo: Advanced Example"
execute = true

[d5]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh append_to_command"
description = "Demo: Append to Command"
execute = true

[d6]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh surround_command"
description = "Demo: Surround Command"
execute = true

[d7]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh panel"
description = "Demo: Panel"
execute = true

[d8]
command = "bash $LEADR_CONFIG_DIR/explain_demo.sh thanks"
description = "Demo: Thanks For Watching!"
execute = true

[fl]
command = " | fzf | awk '{print $#CURSOR}'"
description = "Fuzzy find column in list"
insert_type = "Append"

[gl]
command = "git log --oneline"
description = "Compact git log"
execute = true

[gs]
command = "git status"
description = "Git status"
execute = true

[gc]
command = 'git commit -m "#CURSOR"'
description = "Start a git commit"

[id]
command = "date +%Y-%m-%d"
description = "Insert current date"
insert_type = "Insert"
evaluate = true

[ra]
command = "Never"

[rb]
command = "Gonna"

[rc]
command = "Give"

[rd]
command = "You"

[re]
command = "Up"

[rf]
command = "Never"

[rg]
command = "Gonna"

[rh]
command = "Let"

[ri]
command = "You"

[rj]
command = "Down"

[cs]
command = "#CURSOR $(#COMMAND)"
description = "Command substitution"
insert_type = "Surround"
